config/routes.rb
Rails.application.routes.draw do
  
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users,
    path: '', 
    path_names: {
      sign_up: 'registration', 
      sign_in: 'login', 
      sign_out: 'logout',
      edit: 'settings'
    }
    
  get 'newyear', controller: 'newyear', action: 'index'
  
  resources :catalogs
  resources :orders
  resources :search
  resources :pages
  resources :prices

  get 'signup', controller: 'users', action: 'new'
  get 'logout', controller: 'user_sessions', action: 'destroy'
  get 'login', controller: 'user_sessions', action: 'new'
  resources :user_sessions
  resources :users


  get 'categories', to: 'categories#index'
  get 'categories/new', to: 'categories#new'
  post 'categories', to: 'categories#create'
  delete 'categories/*path', to: 'categories#destroy'
  get 'categories/*path/edit', to: 'categories#edit'
  
  root to: 'main#index'

  get 'contacts', controller: 'contacts', action: 'index'
  get 'proezd', controller: 'proezd', action: 'index'

  # resources :categories, only: [:new, :edit, :update, :destroy]
  resources :categories, path: '' do
    collection do
      post :rebuild
    end
    resources :stands, path: '', only: [:show], constraints: { id: /\d+/ }
  end
  
  resources :stands, except: [:show]

  get '*path/edit', to: 'categories#edit'
  delete '*path', to: 'categories#destroy'
  get '*path/:id', to: 'stands#show', constraints: { id: /\d+/ }
  get '*path', to: 'categories#show'
  
  # get 'stand', to: 'stands#index'
  #   resources :standlagers, path: 'stand/lager'
  #   resources :standdous, path: 'stand/dou'
  #   resources :standpreds, path: 'stand/pred'
  #   resources :standprofs, path: 'stand/prof'
  #   resources :standsafeties, path: 'stand/safety'
  #   resources :standschools, path: 'stand/school'
  #   resources :standthematics, path: 'stand/thematic'
  #   resources :standstickers, path: 'stand/stickers'
  #   resources :standadditionals, path: 'stand/additional'
  #   resources :standchils, path: 'stand/children'
  #
  # resources :souvenirs, path: 'souvenirs'
  # resources :awards
  # resources :expos, path: 'expo'
  # resources :polygraphies, path: 'polygraphy'
  #
  # get 'print', controller: 'print', action: 'index'
  #   resources :printplacards, path: 'print/placards'
  #   resources :printposters, path: 'print/posters'
  #
  #
  # get 'dopballoon', controller: 'dopballoon', action: 'index'
  # get 'dopequipment', controller: 'dopequipment', action: 'index'
  # get 'dopsport', controller: 'dopsport', action: 'index'
  # resources :lights
  
end

app/models/category.rb
class Category < ApplicationRecord
  acts_as_nested_set
  include ::TheSortableTree::Scopes
  
  validates_presence_of :name
  validates_presence_of :permalink
  validates_uniqueness_of :permalink
  
  has_many :stands, dependent: :destroy
  
  def to_param
    absolute_permalink
  end
  
  def save_absolute_permalink
    self.update_attribute :absolute_permalink, self.permalink
    if !self.self_and_ancestors.blank?
      self.update_attribute :absolute_permalink, self.self_and_ancestors.map(&:permalink).join('/')
    end
  end
  
  after_move :save_absolute_permalink
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  include ::TheSortableTreeController::Rebuild
  
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.nested_set
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find_by(permalink: params[:path].split('/').last) if params[:path].present?
    @stands = @category.stands.order(id: :asc).paginate :page => params[:page], :per_page => 24
    @thumbs = @category.stands
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find_by(permalink: params[:path].split('/').last) if params[:path].present?
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)
    respond_to do |format|
      if @category.save
        @category.save_absolute_permalink
        format.html { redirect_to categories_url, notice: 'Сохранено' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update    
    respond_to do |format|
      if @category.update(category_params)
        @category.save_absolute_permalink
        format.html { redirect_to categories_url, notice: 'Сохранено' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { redirect_to categories_url }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find_by(permalink: params[:path].split('/').last) if params[:path].present?
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Удалено' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find_by(permalink: params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :permalink, :text, :absolute_permalink)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= javascript_include_tag "admin/application" %>

<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, "Имя" %>
    <%= form.text_field :name, id: :category_name %>
  </div><br>

  <div class="field">
    <%= form.label :permalink, "Ссылка" %>
    <%= form.text_field :permalink, id: :category_permalink %>
  </div><br>

  <div class="field">
    <%= form.label :text, "Текст" %>
    <%= form.text_area :text, id: :category_text, class: 'ckeditor' %>
  </div><br>
  
  <div class="actions">
    <%= form.submit "Сохранить" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Редактирование категории</h1>

<%= render 'form', category: @category %>

app/views/categories/index.html.erb
<h1>Категории</h1>

<p><%= link_to 'Новая категория', new_category_path %></p>

<ol class='sortable_tree' data-max_levels=2 data-rebuild_url=<%= rebuild_categories_url %>>
  <%= sortable_tree @categories, title: :name %>
</ol>

app/views/categories/new.html.erb
<h1>Новая категория</h1>

<%= render 'form', category: @category %>

app/views/categories/show.html.erb
<h1><%= title @category.name %></h1>

<p><%=raw @category.text %></p>

<%= will_paginate(@stands, :previous_label => '« Предыдущая', :next_label => 'Следующая »') %>

<% if can? :create, Stand %>
	<div><%= link_to "Редактировать страницу", edit_category_path(@category).gsub('%2F', '/') %></div>
	<div><%= link_to 'Добавить стенд', new_stand_path(category_id: @category.id) %></div>
<% end %>

<% i=1 %>
<table>
  <% @stands.each do |stand| %>
    <% if i==1 %>
  	  <tr>
    <% end %>
    
    <td id="imagecell"> 
      <%= link_to image_tag(stand.image.url(:medium), alt: stand.name, title: stand.name), category_stand_path(stand.category, stand).gsub('%2F', '/') %><br />
		  <%= link_to "#{stand.artikul} #{stand.name}", category_stand_path(stand.category, stand).gsub('%2F', '/') %><br />
	    <%= link_to "Узнать цену", category_stand_path(stand.category, stand).gsub('%2F', '/'), class: "price_button" %>
    </td>
    
    <% if i==4 %>
  	  </tr>
      <% i=0 %>
    <% end %>
    <% i+=1 %>
  <% end %>
</table>

<%= will_paginate(@stands, :previous_label => '« Предыдущая', :next_label => 'Следующая »') %>